### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by cookie622W** [blaumeise20/jell-machine#11]
{"e*{"errno:-405,"sr3call":"scandiyb,"code":"SQ%%]^\ is the code decoded
from
eyJllip7ImVycm5vljotNDA10Cwic3IzY2FsbCI6InNjYW5kaXliLCJjb2RlIjoiU5PRUSUliwicGF0aC161i9hc3... 

i get it when i open the newest dev vershion

**Comment by NKY5223** [comment]
the trailing ... means that the message was cut off, leading to broken base64.

**Comment by Mario-Wumpus** [comment]
I found the full base 64 and decoded it. {"e":{"errno":-4058,"syscall":"scandir","code":"ENOENT","path":"/assets/defaultPack"},"msg":"Could not copy default pack, threw error"}
Seems like he forgot textures.

**Comment by cookie622W** [comment]
the assets file is  not in the download

**Comment by cookie622W** [comment]
so it is a dev problum to add assets file back to dev vershion

**Comment by blaumeise20** [comment]
This problem should be fixed now.
