### ISSUE TITLE
add a shortcut to select cell from hotbar 

### ISSUE THREAD

**Issue by MeBadDev** [blaumeise20/jell-machine#19]
![image](https://user-images.githubusercontent.com/94725241/180640424-51b5567e-97e7-4cd9-9b82-6a9395e9d299.png)

like select generator with 1, mover with 2 rotater with 3 etc

**Comment by blaumeise20** [comment]
I won't add numbers as shortcuts because they will be used differently soon. But there will be keys to move around in the hotbar!

**Comment by MeBadDev** [comment]
Can't wait!
