### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by toobdev1** [blaumeise20/jell-machine#2]

**Comment by blaumeise20** [comment]
Please describe your problem properly!

**Comment by toobdev1** [comment]
Well, I do not know how to run Jell Machine, can you help?

**Comment by blaumeise20** [comment]
You have to download the .zip file for your system and extract it. Then you can just double-click "Jell Machine.whatever".

**Comment by toobdev1** [comment]
> You have to download the .zip file for your system and extract it. Then you can just double-click "Jell Machine.whatever".

Didn't work

**Comment by toobdev1** [comment]
> You have to download the .zip file for your system and extract it. Then you can just double-click "Jell Machine.whatever".

I'm on windows.

**Comment by TheEt1234** [comment]
> > You have to download the .zip file for your system and extract it. Then you can just double-click "Jell Machine.whatever".
> 
> I'm on windows.

So then download the zip file for windows

and **extract it**

Once it's extracted to a folder

Go to the folder

double click JellMachine.exe or whatever

**Comment by z0rliss** [comment]
there is no .exe file or folder, its just Frameworks, MacOS, Resources

idk how to open it

**Comment by blaumeise20** [comment]
You have to download the Windows version! It seems like you downloaded darwin.
