### ISSUE TITLE
Jell Machine infinitely loading on MacOS 11

### ISSUE THREAD

**Issue by retest672** [blaumeise20/jell-machine#24]
### Jell Machine infinitely loading on MacOS 11.0
**Issue:**
Jell Machine standalone app does open, but loads infinitely. Website version works just fine.

**Version:**
MacOS 11.0 (20A2411), Jell Machine v1.1.1, Chrome 108.0.5359.124

**Computer:**
MacBook Air (M1, 2020)

**Steps to reproduce:**
Open jell machine standalone app (maybe computer-side or version-side issue)

**Videos:**

https://user-images.githubusercontent.com/87881241/210160356-989e1c50-94d0-44a2-8d5e-799edddc51a4.mov

https://user-images.githubusercontent.com/87881241/210160374-57ddcb9a-943f-48b0-80f3-0e6579e0739e.mp4

**Comment by frinkifail** [comment]
just wondering, where did you put the Jell Machine app?

**Comment by retest672** [comment]
hold on just redownloading it and testing it in the applications folder

**Comment by retest672** [comment]
yep still doesn't work

**Comment by retest672** [comment]
even with quarantine removed

**Comment by retest672** [comment]
even compiling it myself doesn't work

**Comment by retest672** [comment]
well, now that i think about it, it could be a computer-side or macOS version-side issue

**Comment by blaumeise20** [comment]
Everything works fine for me (I also use MacOS), did you try updating your system to a newer version?

**Comment by retest672** [comment]
I simply cannot. It will not let me update the system. Maybe it is a version-side issue. Maybe I will just use the web version. Thanks!

**Comment by retest672** [comment]
It will not let me update the system, so I don't know. So I'm just gonna use the web version for now. Thanks though!
