### ISSUE TITLE
please make version for web

### ISSUE THREAD

**Issue by michaelwithab** [blaumeise20/jell-machine#5]
please and thank you :D

**Comment by NKY5223** [comment]
ehe

**Comment by blaumeise20** [comment]
Yes I will do that. Already planned 😀

**Comment by yaay1010** [comment]
hi this is his alt, just wanna say gl on the web version

**Comment by NKY5223** [comment]
> hi this is his alt, just wanna say gl on the web version

will @blaumeise20 use WebGL?

**Comment by uku1928** [comment]
no, he probably won't do a web version

**Comment by blaumeise20** [comment]
I will.

**Comment by frinkifail** [comment]
[Jell Machine](https://jell-machine.com)

**Comment by frinkifail** [comment]
please close this issue!
